import Foundation
import CryptoKit

/// Verifies GDC-format license serials — a Swift port of
/// gdc-license-system's `license_core.py` (`validate_serial_compact`,
/// the same machine-locked format `license_check.cpp` uses for
/// gdc-resolve-encoder), kept byte-for-byte compatible so codes
/// generated by the existing Python tooling (`sell.py`) work here
/// unchanged, and so every GDC product can keep sharing one signing key,
/// one admin tool, and one sales log (`customers.csv`).
///
/// Format: Base32(dash-grouped) of
/// `[4-byte product hash][8-byte big-endian expiry][4-byte nonce][6-byte machine hash][64-byte Ed25519 signature]`
/// — 22 + 64 = 86 raw bytes. Product hash = SHA-512(product id)[:4].
/// Machine hash = SHA-512(hardware UUID)[:6], or all-zero if the code
/// isn't locked to one Mac (see `MachineID.swift`).
///
/// Verification only ever uses the PUBLIC key — the private key that
/// signs new codes stays on Cristi's machine in `gdc-license-system/`,
/// never in this app.
public enum LicenseCore {
    /// GDC-LICENSE-PLATFORM (Etapa 2, 2026-08-25): al 23-lea octet, ADAUGAT
    /// la finalul payload-ului v1 (22 octeti), niciodata repurposand nonce-ul
    /// existent — vezi nota de compatibilitate de mai jos.
    ///   0 = legacy/oricare platforma (identic cu absenta bitului — orice
    ///       cod v1, deja emis, se comporta EXACT ca inainte)
    ///   1 = mac_only
    ///   2 = windows_only
    ///   3 = cross_platform (Mac + Windows, acelasi cod)
    public enum LicensePlatform: UInt8 {
        case any = 0
        case macOnly = 1
        case windowsOnly = 2
        case crossPlatform = 3

        /// Platforma pe care ruleaza acest binar — comparata la validare.
        static var current: LicensePlatform { .macOnly } // acest target compileaza DOAR pe macOS

        func allows(_ current: LicensePlatform) -> Bool {
            self == .any || self == .crossPlatform || self == current
        }
    }

    public struct Payload {
        public let expiresAt: Int64 // unix seconds, 0 = never expires
        public let machineLocked: Bool
        public let platform: LicensePlatform

        public init(expiresAt: Int64, machineLocked: Bool, platform: LicensePlatform = .any) {
            self.expiresAt = expiresAt
            self.machineLocked = machineLocked
            self.platform = platform
        }
    }

    public enum ValidationError: Error {
        case malformedCode
        case badSignature
        case wrongProduct
        /// Codul e valid, dar emis pentru alta platforma (ex. windows_only
        /// activat pe Mac). Codurile v1 (fara byte de platforma) nu pot
        /// avea niciodata aceasta eroare — decodeaza mereu ca `.any`.
        case wrongPlatform(Payload)
        /// Carries the parsed Payload — LicenseManager needs it to decide
        /// kill-switch policy (demo mode) without re-parsing.
        case wrongMachine(Payload)
        /// GDC-SEC (kill-switch diferentiat, 2026-08-24): IOKit couldn't
        /// answer just now — distinct from wrongMachine so a transient
        /// read failure never mistakes an honest customer's Mac for a
        /// different one. See LicenseManager.swift for grace-period logic.
        case hwidUnavailable(Payload)
        case expired(Int64, Payload)
    }

    /// Base64 of the Ed25519 PUBLIC key from gdc-license-system's
    /// keygen.py (`public_key.txt`). Safe to embed: with asymmetric
    /// crypto, only the never-distributed private key can forge a
    /// signature this validates. Shared by both the client app (to
    /// verify) and, indirectly, the vendor app (whose private key must
    /// match this one — see GDCPluginManagerFurnizor/LicenseGenerator.swift).
    static let publicKeyBase64 = "I1h23MNMRbOhc0ObKJrfa3oFHKA9w+SzbNrroAIy8hs="

    /// Exposed so the vendor app's LicenseGenerator can build the exact
    /// same payload shape when signing new codes. `payloadSize` ramane
    /// dimensiunea v1 (neschimbata — orice cod deja emis foloseste asta);
    /// `payloadSizeV2` e dimensiunea noilor coduri, cu byte-ul de platforma
    /// ADAUGAT la finalul payload-ului v1, nu suprascriind nimic existent.
    public static let payloadSize = 22
    public static let payloadSizeV2 = 23

    /// Validates a serial the user typed/pasted against `expectedProductID`.
    /// `hwidAvailable` (default true, i.e. unchanged for interactive
    /// activation) lets LicenseManager's periodic re-check pass `false`
    /// when IOKit couldn't answer just now — see `.hwidUnavailable` above.
    ///
    /// GDC-LICENSE-PLATFORM: accepta AMBELE dimensiuni de payload —
    /// 86 octeti bruti (22+64, coduri v1, deja emise) si 87 (23+64, coduri
    /// noi, cu platforma). Un cod v1 decodeaza mereu platforma ca `.any`,
    /// deci comportamentul lui ramane identic dinainte de aceasta schimbare
    /// — nicio licenta existenta nu poate fi blocata retroactiv.
    public static func validate(serial: String, expectedProductID: String, hwidAvailable: Bool = true) -> Result<Payload, ValidationError> {
        guard let packed = base32Decode(serial) else {
            return .failure(.malformedCode)
        }
        let effectiveSize: Int
        if packed.count == payloadSize + 64 {
            effectiveSize = payloadSize
        } else if packed.count == payloadSizeV2 + 64 {
            effectiveSize = payloadSizeV2
        } else {
            return .failure(.malformedCode)
        }
        let payloadBytes = packed.prefix(effectiveSize)
        let signature = packed.suffix(64)

        guard let publicKeyData = Data(base64Encoded: publicKeyBase64),
              let publicKey = try? Curve25519.Signing.PublicKey(rawRepresentation: publicKeyData) else {
            return .failure(.malformedCode)
        }
        guard publicKey.isValidSignature(signature, for: payloadBytes) else {
            return .failure(.badSignature)
        }

        let bytes = Array(payloadBytes)
        let storedProductHash = bytes[0..<4]
        let expectedProductHash = productHash(for: expectedProductID)
        guard Array(storedProductHash) == expectedProductHash else {
            return .failure(.wrongProduct)
        }

        var expiresAt: Int64 = 0
        for i in 4..<12 { expiresAt = (expiresAt << 8) | Int64(bytes[i]) }

        let storedMachineHash = Array(bytes[16..<22])
        let isMachineLocked = storedMachineHash.contains { $0 != 0 }
        let platform: LicensePlatform = (effectiveSize == payloadSizeV2)
            ? (LicensePlatform(rawValue: bytes[22]) ?? .any)
            : .any
        let payload = Payload(expiresAt: expiresAt, machineLocked: isMachineLocked, platform: platform)

        guard platform.allows(.current) else {
            return .failure(.wrongPlatform(payload))
        }

        if isMachineLocked {
            guard hwidAvailable else {
                return .failure(.hwidUnavailable(payload))
            }
            guard storedMachineHash == MachineID.hashBytes else {
                return .failure(.wrongMachine(payload))
            }
        }

        if expiresAt != 0 && expiresAt < Int64(Date().timeIntervalSince1970) {
            return .failure(.expired(expiresAt, payload))
        }
        return .success(payload)
    }

    /// Exposed so the vendor app's LicenseGenerator computes the exact
    /// same product hash when signing a new code for a given product ID.
    public static func productHash(for productID: String) -> [UInt8] {
        Array(SHA512.hash(data: Data(productID.utf8)).prefix(4))
    }

    // MARK: - Base32 (RFC 4648, matching Python's base64.b32encode/decode)

    private static let base32Alphabet = Array("ABCDEFGHIJKLMNOPQRSTUVWXYZ234567")

    public static func base32Encode(_ data: Data) -> String {
        var bits = 0, value = 0
        var output = ""
        for byte in data {
            value = (value << 8) | Int(byte)
            bits += 8
            while bits >= 5 {
                output.append(base32Alphabet[(value >> (bits - 5)) & 0x1F])
                bits -= 5
            }
        }
        if bits > 0 {
            output.append(base32Alphabet[(value << (5 - bits)) & 0x1F])
        }
        return output
    }

    /// Exposed so the vendor app's LicenseGenerator can decode a pasted
    /// machine-ID string into the 6 raw bytes it needs to embed.
    public static func base32Decode(_ string: String) -> Data? {
        let cleaned = string.uppercased()
            .replacingOccurrences(of: "-", with: "")
            .replacingOccurrences(of: " ", with: "")
            .replacingOccurrences(of: "=", with: "")
        var bits = 0, value = 0
        var output = [UInt8]()
        for char in cleaned {
            guard let index = base32Alphabet.firstIndex(of: char) else { return nil }
            value = (value << 5) | index
            bits += 5
            if bits >= 8 {
                output.append(UInt8((value >> (bits - 8)) & 0xFF))
                bits -= 8
            }
        }
        return Data(output)
    }
}
